VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "objArquiteto"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public codigo As String
Public nome As String
Public escritorio As String
Public aniversario As String
Public ultimoContato As String
Public marmoarias As String
Public observacaoGeral As String
Public retorno As String
Public pendencia As String
Public email As String
Public telefone As String
Public cpf As String
Public cnpj As String
Public logradouro As String
Public bairro As String
Public cidade As String
Public uf As String
Public cep As String
Public listaContatos As Collection
Public listaRomaneios As Collection


