VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "objContato"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public codigo As String
Public dataContato As String
Public relatoContato As String
Public dataRetorno As String
Public obsevacao As String
Public arquiteto As objArquiteto


